<h2>Izvērtēšana</h2>

In [0]:
from google.colab import drive
import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
drive.mount('/gdrive')
%cd '/gdrive/My Drive/LU/LU DF/8. semestris/Bakalaura Darbs/Datasets/BERT_encoded'

In [0]:
%cd '/gdrive/My Drive/LU/LU DF/8. semestris/Bakalaura Darbs/Datasets/'
eval_data = pd.read_csv('2020_05_24_BERT_small_izvertesana.csv', index_col=0)
col_count = len(eval_data.columns) - 1
X = eval_data.iloc[:,:col_count]
Y = eval_data.iloc[:,col_count:]
print(X.shape, Y.shape)

/gdrive/My Drive/LU/LU DF/8. semestris/Bakalaura Darbs/Datasets
(100, 256) (100, 1)


In [0]:
def transformResults(results):
    mod_results = []
    for result in results:
        out = np.argmax(result)
        mod_results.append(out)
    mod_results = np.array(mod_results)    
    return mod_results 

<h3>Nepapildināto jautājumu izvērtēšana</h3>

In [0]:
sakotnejie = pd.read_csv('Encoded_labeled_BERT_small.csv', index_col=0)
print(sakotnejie.shape)
col_count = len(sakotnejie.columns) - 1
features = sakotnejie.iloc[:,:col_count]
target = sakotnejie.iloc[:,col_count:]
print(features.shape, target.shape)

(23217, 257)
(23217, 256) (23217, 1)


In [0]:
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
y_test = Y.to_numpy()

model_scores = []
counter = 0
for i in range(10):
  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(features, target,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT small scores:', model_scores)
print('BERT small final score:',f1_final_score)

(100, 256) (100, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT small scores: [0.1, 0.2542, 0.3693, 0.12, 0.3354, 0.2516, 0.3815, 0.2401, 0.4281, 0.3008]
BERT small final score: 0.28


In [0]:
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.4583
              precision    recall  f1-score   support

  akadēmisks       1.00      0.32      0.48        25
        citi       0.32      1.00      0.49        25
 darba laiks       1.00      0.36      0.53        25
   dokumenti       1.00      0.20      0.33        25

    accuracy                           0.47       100
   macro avg       0.83      0.47      0.46       100
weighted avg       0.83      0.47      0.46       100

[[ 8 17  0  0]
 [ 0 25  0  0]
 [ 0 16  9  0]
 [ 0 20  0  5]]
[[0.32 0.68 0.   0.  ]
 [0.   1.   0.   0.  ]
 [0.   0.64 0.36 0.  ]
 [0.   0.8  0.   0.2 ]]


<h2>Papildināto jautājumu izvērtēšana</h2>

In [0]:
%cd '/gdrive/My Drive/LU/LU DF/8. semestris/Bakalaura Darbs/Datasets/BERT_encoded'
papildinatie = pd.read_csv('2020_05_10_encoded_BERT_small.csv', index_col=0)
print(papildinatie.shape)
col_count = len(papildinatie.columns) - 1
features = papildinatie.iloc[:,:col_count]
target = papildinatie.iloc[:,col_count:]
print(features.shape, target.shape)

/gdrive/My Drive/LU/LU DF/8. semestris/Bakalaura Darbs/Datasets/BERT_encoded
(23391, 257)
(23391, 256) (23391, 1)


In [0]:
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
y_test = Y.to_numpy()

model_scores = []
counter = 0
for i in range(10):
  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(features, target,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT small scores:', model_scores)
print('BERT small final score:',f1_final_score)

(100, 256) (100, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT small scores: [0.7004, 0.5893, 0.625, 0.4848, 0.6802, 0.6722, 0.6543, 0.6428, 0.7238, 0.7247]
BERT small final score: 0.65


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.534
              precision    recall  f1-score   support

  akadēmisks       1.00      0.72      0.84        25
        citi       0.37      1.00      0.54        25
 darba laiks       1.00      0.04      0.08        25
   dokumenti       1.00      0.52      0.68        25

    accuracy                           0.57       100
   macro avg       0.84      0.57      0.53       100
weighted avg       0.84      0.57      0.53       100

[[18  7  0  0]
 [ 0 25  0  0]
 [ 0 24  1  0]
 [ 0 12  0 13]]
[[0.72 0.28 0.   0.  ]
 [0.   1.   0.   0.  ]
 [0.   0.96 0.04 0.  ]
 [0.   0.48 0.   0.52]]


<h2>UnderSampling izvērtēšana</h2>

In [0]:
from imblearn.under_sampling import NearMiss
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

model_scores = []
counter = 0
for i in range(10):
  undersampler = NearMiss()
  X_res, y_res = undersampler.fit_resample(features, target)                   # Veicam Unersampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT small scores:', model_scores)
print('BERT small final score:',f1_final_score)

(100, 256) (100, 1)
(23391, 256) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT small scores: [0.6557, 0.6032, 0.5926, 0.6255, 0.604, 0.6751, 0.63, 0.6282, 0.6561, 0.6596]
BERT small final score: 0.63


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.6462
              precision    recall  f1-score   support

  akadēmisks       0.56      1.00      0.71        25
        citi       0.80      0.16      0.27        25
 darba laiks       0.72      0.84      0.78        25
   dokumenti       0.90      0.76      0.83        25

    accuracy                           0.69       100
   macro avg       0.75      0.69      0.65       100
weighted avg       0.75      0.69      0.65       100

[[25  0  0  0]
 [11  4  8  2]
 [ 4  0 21  0]
 [ 5  1  0 19]]
[[1.   0.   0.   0.  ]
 [0.44 0.16 0.32 0.08]
 [0.16 0.   0.84 0.  ]
 [0.2  0.04 0.   0.76]]


<h2>OverSampling izvērtēšana</h2>

<h3>Oversampling apjoms = 100%</h3>

In [0]:
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 2*122
thisdict = {
  1: 23025,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)

model_scores = []
counter = 0
for i in range(10):
  undersampler = NearMiss()
  X_res, y_res = oversampler.fit_resample(features, target)                       # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT small scores:', model_scores)
print('BERT small final score:',f1_final_score)

(100, 256) (100, 1)
(23391, 256) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT small scores: [0.6526, 0.6735, 0.6673, 0.5794, 0.681, 0.6289, 0.7103, 0.6989, 0.6002, 0.7359]
BERT small final score: 0.66


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.618
              precision    recall  f1-score   support

  akadēmisks       1.00      0.72      0.84        25
        citi       0.40      0.96      0.56        25
 darba laiks       1.00      0.24      0.39        25
   dokumenti       0.88      0.56      0.68        25

    accuracy                           0.62       100
   macro avg       0.82      0.62      0.62       100
weighted avg       0.82      0.62      0.62       100

[[18  6  0  1]
 [ 0 24  0  1]
 [ 0 19  6  0]
 [ 0 11  0 14]]
[[0.72 0.24 0.   0.04]
 [0.   0.96 0.   0.04]
 [0.   0.76 0.24 0.  ]
 [0.   0.44 0.   0.56]]


<h3>Oversampling apjoms = 200%</h3>

In [0]:
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 3*122
thisdict = {
  1: 23025,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)

model_scores = []
counter = 0
for i in range(10):
  undersampler = NearMiss()
  X_res, y_res = oversampler.fit_resample(features, target)                       # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT small scores:', model_scores)
print('BERT small final score:',f1_final_score)

(100, 256) (100, 1)
(23391, 256) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT small scores: [0.7127, 0.5599, 0.6326, 0.6922, 0.5881, 0.7341, 0.7773, 0.7232, 0.6494, 0.6987]
BERT small final score: 0.68


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
print(X.shape, Y.shape)
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

(100, 256) (100, 1)
Naive Bayes F1 score: 0.7033
              precision    recall  f1-score   support

  akadēmisks       0.95      0.80      0.87        25
        citi       0.46      0.96      0.62        25
 darba laiks       1.00      0.36      0.53        25
   dokumenti       0.94      0.68      0.79        25

    accuracy                           0.70       100
   macro avg       0.84      0.70      0.70       100
weighted avg       0.84      0.70      0.70       100

[[20  5  0  0]
 [ 0 24  0  1]
 [ 0 16  9  0]
 [ 1  7  0 17]]
[[0.8  0.2  0.   0.  ]
 [0.   0.96 0.   0.04]
 [0.   0.64 0.36 0.  ]
 [0.04 0.28 0.   0.68]]


<h3>Oversampling apjoms = 300%</h3>

In [0]:
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 4*122
thisdict = {
  1: 23025,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)

model_scores = []
counter = 0
for i in range(10):
  undersampler = NearMiss()
  X_res, y_res = oversampler.fit_resample(features, target)                       # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT small scores:', model_scores)
print('BERT small final score:',f1_final_score)

(100, 256) (100, 1)
(23391, 256) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT small scores: [0.67, 0.6554, 0.7213, 0.7069, 0.7583, 0.6852, 0.545, 0.6917, 0.7253, 0.7176]
BERT small final score: 0.69


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.7535
              precision    recall  f1-score   support

  akadēmisks       1.00      0.84      0.91        25
        citi       0.49      0.92      0.64        25
 darba laiks       0.93      0.56      0.70        25
   dokumenti       0.94      0.64      0.76        25

    accuracy                           0.74       100
   macro avg       0.84      0.74      0.75       100
weighted avg       0.84      0.74      0.75       100

[[21  4  0  0]
 [ 0 23  1  1]
 [ 0 11 14  0]
 [ 0  9  0 16]]
[[0.84 0.16 0.   0.  ]
 [0.   0.92 0.04 0.04]
 [0.   0.44 0.56 0.  ]
 [0.   0.36 0.   0.64]]


<h1>Kombinētā Under & Over Sampling izvērtēšana</h1>

<h3>Oversampling apjoms = 100%</h3>

In [0]:
from imblearn.under_sampling import NearMiss
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 2*122
thisdict = {
  1: size,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)
undersampler = NearMiss()

model_scores = []
counter = 0
for i in range(10):
  X_res, y_res = undersampler.fit_resample(features, target)                      # Veicam Unersampling
  X_res, y_res = oversampler.fit_resample(X_res, y_res)                           # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT small scores:', model_scores)
print('BERT small final score:',f1_final_score)

(100, 256) (100, 1)
(23391, 256) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT small scores: [0.7148, 0.665, 0.6462, 0.7011, 0.665, 0.6474, 0.6908, 0.7107, 0.6861, 0.6485]
BERT small final score: 0.68


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.6858
              precision    recall  f1-score   support

  akadēmisks       0.77      0.96      0.86        25
        citi       0.71      0.20      0.31        25
 darba laiks       0.67      0.88      0.76        25
   dokumenti       0.76      0.88      0.81        25

    accuracy                           0.73       100
   macro avg       0.73      0.73      0.69       100
weighted avg       0.73      0.73      0.69       100

[[24  0  1  0]
 [ 4  5 10  6]
 [ 2  0 22  1]
 [ 1  2  0 22]]
[[0.96 0.   0.04 0.  ]
 [0.16 0.2  0.4  0.24]
 [0.08 0.   0.88 0.04]
 [0.04 0.08 0.   0.88]]


<h3>Oversampling apjoms = 300%</h3>

In [0]:
from imblearn.under_sampling import NearMiss
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 3*122
thisdict = {
  1: size,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)
undersampler = NearMiss()

model_scores = []
counter = 0
for i in range(10):
  X_res, y_res = undersampler.fit_resample(features, target)                      # Veicam Unersampling
  X_res, y_res = oversampler.fit_resample(X_res, y_res)                           # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT small scores:', model_scores)
print('BERT small final score:',f1_final_score)

(100, 256) (100, 1)
(23391, 256) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT small scores: [0.6917, 0.6663, 0.6753, 0.6754, 0.6746, 0.6829, 0.6951, 0.6765, 0.6723, 0.7096]
BERT small final score: 0.68


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.6852
              precision    recall  f1-score   support

  akadēmisks       0.80      0.96      0.87        25
        citi       0.83      0.20      0.32        25
 darba laiks       0.64      0.84      0.72        25
   dokumenti       0.74      0.92      0.82        25

    accuracy                           0.73       100
   macro avg       0.75      0.73      0.69       100
weighted avg       0.75      0.73      0.69       100

[[24  0  1  0]
 [ 3  5 11  6]
 [ 2  0 21  2]
 [ 1  1  0 23]]
[[0.96 0.   0.04 0.  ]
 [0.12 0.2  0.44 0.24]
 [0.08 0.   0.84 0.08]
 [0.04 0.04 0.   0.92]]


<h3>Oversampling apjoms = 300%</h3>

In [0]:
from imblearn.under_sampling import NearMiss
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 4*122
thisdict = {
  1: size,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)
undersampler = NearMiss()

model_scores = []
counter = 0
for i in range(10):
  X_res, y_res = undersampler.fit_resample(features, target)                      # Veicam Unersampling
  X_res, y_res = oversampler.fit_resample(X_res, y_res)                           # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT small scores:', model_scores)
print('BERT small final score:',f1_final_score)

(100, 256) (100, 1)
(23391, 256) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT small scores: [0.6706, 0.712, 0.6483, 0.6826, 0.6915, 0.6951, 0.6297, 0.6933, 0.6915, 0.6652]
BERT small final score: 0.68


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.6463
              precision    recall  f1-score   support

  akadēmisks       0.86      0.96      0.91        25
        citi       1.00      0.08      0.15        25
 darba laiks       0.68      0.84      0.75        25
   dokumenti       0.64      1.00      0.78        25

    accuracy                           0.72       100
   macro avg       0.79      0.72      0.65       100
weighted avg       0.79      0.72      0.65       100

[[24  0  0  1]
 [ 3  2 10 10]
 [ 1  0 21  3]
 [ 0  0  0 25]]
[[0.96 0.   0.   0.04]
 [0.12 0.08 0.4  0.4 ]
 [0.04 0.   0.84 0.12]
 [0.   0.   0.   1.  ]]
