<h2>Izvērtēšana</h2>

In [0]:
from google.colab import drive
import numpy as np
import pandas as pd
import datetime
import warnings
warnings.filterwarnings('ignore')
drive.mount('/gdrive')
%cd '/gdrive/My Drive/LU/LU DF/8. semestris/Bakalaura Darbs/Datasets/BERT_encoded'

<h3>Nepapildināto jautājumu izvērtēšana</h3>

In [0]:
sakotnejie = pd.read_csv('Encoded_labeled_BERT_big.csv', index_col=0)
print(sakotnejie.shape)
sakotnejie.head(3)

(23217, 769)


0         1         2         3  ...       765       766       767  labels
0  0.679284 -0.400574 -0.620375  0.611502  ... -0.809350  0.006495 -0.047038       2
1  1.461980 -0.126122 -1.126548 -0.067945  ... -1.755251 -0.951623 -0.562593       2
2  0.406492 -0.314168 -0.871162  0.276910  ... -0.613054 -0.268880 -0.104552       2

[3 rows x 769 columns]

In [0]:
col_count = len(sakotnejie.columns) - 1
print(col_count)
features = sakotnejie.iloc[:,:col_count]
target = sakotnejie.iloc[:,col_count:]
print(features.shape, target.shape)

768
(23217, 768) (23217, 1)


In [0]:
%cd '/gdrive/My Drive/LU/LU DF/8. semestris/Bakalaura Darbs/Datasets/'
eval_data = pd.read_csv('2020_05_24_BERT_big_izvertesana.csv', index_col=0)
eval_data['labels'].value_counts()
col_count = len(eval_data.columns) - 1
X = eval_data.iloc[:,:col_count]
Y = eval_data.iloc[:,col_count:]
print(X.shape, Y.shape)

/gdrive/My Drive/LU/LU DF/8. semestris/Bakalaura Darbs/Datasets
(100, 768) (100, 1)


In [0]:
def transformResults(results):
    mod_results = []
    for result in results:
        out = np.argmax(result)
        mod_results.append(out)
    mod_results = np.array(mod_results)    
    return mod_results 

In [0]:
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
y_test = Y.to_numpy()

model_scores = []
counter = 0
for i in range(10):
  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(features, target,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                     # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                       # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)             # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT big final score:',f1_final_score)

(100, 768) (100, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT big final score: 0.43


In [0]:
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)         # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.4525
              precision    recall  f1-score   support

  akadēmisks       1.00      0.28      0.44        25
        citi       0.32      1.00      0.49        25
 darba laiks       1.00      0.44      0.61        25
   dokumenti       1.00      0.16      0.28        25

    accuracy                           0.47       100
   macro avg       0.83      0.47      0.45       100
weighted avg       0.83      0.47      0.45       100

[[ 7 18  0  0]
 [ 0 25  0  0]
 [ 0 14 11  0]
 [ 0 21  0  4]]
[[0.28 0.72 0.   0.  ]
 [0.   1.   0.   0.  ]
 [0.   0.56 0.44 0.  ]
 [0.   0.84 0.   0.16]]


<h2>Papildināto jautājumu izvērtēšana</h2>

In [0]:
%cd '/gdrive/My Drive/LU/LU DF/8. semestris/Bakalaura Darbs/Datasets/BERT_encoded'
papildinatie = pd.read_csv('2020_05_10_encoded_BERT_big.csv', index_col=0)
print(papildinatie.shape)
papildinatie['labels'].value_counts()
col_count = len(papildinatie.columns) - 1
features = papildinatie.iloc[:,:col_count]
target = papildinatie.iloc[:,col_count:]
print(features.shape, target.shape)

/gdrive/My Drive/LU/LU DF/8. semestris/Bakalaura Darbs/Datasets/BERT_encoded
(23391, 769)
(23391, 768) (23391, 1)


In [0]:
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
y_test = Y.to_numpy()

model_scores = []
counter = 0
for i in range(10):
  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(features, target,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT big final score:',f1_final_score)

(100, 768) (100, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT big final score: 0.71


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.7315
              precision    recall  f1-score   support

  akadēmisks       1.00      0.72      0.84        25
        citi       0.48      0.96      0.64        25
 darba laiks       1.00      0.48      0.65        25
   dokumenti       0.90      0.72      0.80        25

    accuracy                           0.72       100
   macro avg       0.84      0.72      0.73       100
weighted avg       0.84      0.72      0.73       100

[[18  6  0  1]
 [ 0 24  0  1]
 [ 0 13 12  0]
 [ 0  7  0 18]]
[[0.72 0.24 0.   0.04]
 [0.   0.96 0.   0.04]
 [0.   0.52 0.48 0.  ]
 [0.   0.28 0.   0.72]]


<h2>UnderSampling izvērtēšana</h2>

In [0]:
from imblearn.under_sampling import NearMiss
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

model_scores = []
counter = 0
for i in range(10):
  undersampler = NearMiss()
  X_res, y_res = undersampler.fit_resample(features, target)                   # Veicam Unersampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT big final score:',f1_final_score)

(100, 768) (100, 1)
(23391, 768) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT big final score: 0.68


In [0]:
from sklearn.metrics import f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)         # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.67
              precision    recall  f1-score   support

  akadēmisks       0.75      0.96      0.84        25
        citi       1.00      0.08      0.15        25
 darba laiks       0.75      0.96      0.84        25
   dokumenti       0.74      1.00      0.85        25

    accuracy                           0.75       100
   macro avg       0.81      0.75      0.67       100
weighted avg       0.81      0.75      0.67       100

[[24  0  0  1]
 [ 7  2  8  8]
 [ 1  0 24  0]
 [ 0  0  0 25]]
[[0.96 0.   0.   0.04]
 [0.28 0.08 0.32 0.32]
 [0.04 0.   0.96 0.  ]
 [0.   0.   0.   1.  ]]


<h2>OverSampling izvērtēšana</h2>

<h3>OverSampling apjoms = 100%</h3>

In [0]:
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 2*122
thisdict = {
  1: 23025,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)

model_scores = []
counter = 0
for i in range(10):
  undersampler = NearMiss()
  X_res, y_res = oversampler.fit_resample(features, target)                       # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT big final score:',f1_final_score)

(100, 768) (100, 1)
(23391, 768) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT big final score: 0.77


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.8036
              precision    recall  f1-score   support

  akadēmisks       1.00      1.00      1.00        25
        citi       0.56      0.96      0.71        25
 darba laiks       1.00      0.56      0.72        25
   dokumenti       0.94      0.68      0.79        25

    accuracy                           0.80       100
   macro avg       0.88      0.80      0.80       100
weighted avg       0.88      0.80      0.80       100

[[25  0  0  0]
 [ 0 24  0  1]
 [ 0 11 14  0]
 [ 0  8  0 17]]
[[1.   0.   0.   0.  ]
 [0.   0.96 0.   0.04]
 [0.   0.44 0.56 0.  ]
 [0.   0.32 0.   0.68]]


<h3>OverSampling apjoms = 200%</h3>

In [0]:
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 3*122
thisdict = {
  1: 23025,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)

model_scores = []
counter = 0
for i in range(10):
  undersampler = NearMiss()
  X_res, y_res = oversampler.fit_resample(features, target)                       # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT big final score:',f1_final_score)

(100, 768) (100, 1)
(23391, 768) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT big final score: 0.75


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.8106
              precision    recall  f1-score   support

  akadēmisks       1.00      0.88      0.94        25
        citi       0.56      0.96      0.71        25
 darba laiks       1.00      0.68      0.81        25
   dokumenti       0.94      0.68      0.79        25

    accuracy                           0.80       100
   macro avg       0.88      0.80      0.81       100
weighted avg       0.88      0.80      0.81       100

[[22  3  0  0]
 [ 0 24  0  1]
 [ 0  8 17  0]
 [ 0  8  0 17]]
[[0.88 0.12 0.   0.  ]
 [0.   0.96 0.   0.04]
 [0.   0.32 0.68 0.  ]
 [0.   0.32 0.   0.68]]


<h3>OverSampling apjoms = 300%</h3>

In [0]:
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 4*122
thisdict = {
  1: 23025,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)

model_scores = []
counter = 0
for i in range(10):
  undersampler = NearMiss()
  X_res, y_res = oversampler.fit_resample(features, target)                       # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT big final score:',f1_final_score)

(100, 768) (100, 1)
(23391, 768) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT big final score: 0.77


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

(23391, 768) (23391, 1)
[[    0     1     2     3]
 [  488 23025   488   488]]
Keras Done
Naive Bayes F1 score: 0.818
              precision    recall  f1-score   support

  akadēmisks       1.00      0.96      0.98        25
        citi       0.59      0.96      0.73        25
 darba laiks       1.00      0.48      0.65        25
   dokumenti       0.96      0.88      0.92        25

    accuracy                           0.82       100
   macro avg       0.89      0.82      0.82       100
weighted avg       0.89      0.82      0.82       100

[[24  1  0  0]
 [ 0 24  0  1]
 [ 0 13 12  0]
 [ 0  3  0 22]]
[[0.96 0.04 0.   0.  ]
 [0.   0.96 0.   0.04]
 [0.   0.52 0.48 0.  ]
 [0.   0.12 0.   0.88]]


<h2>Kombinētā Under & Over Sampling izvērtēšana</h2>

<h3>OverSampling apjoms = 100%</h3>

In [0]:
from imblearn.under_sampling import NearMiss
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 2*122
thisdict = {
  1: size,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)
undersampler = NearMiss()

model_scores = []
counter = 0
for i in range(10):
  X_res, y_res = undersampler.fit_resample(features, target)                      # Veicam Unersampling
  X_res, y_res = oversampler.fit_resample(X_res, y_res)                           # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT big final score:',f1_final_score)

(100, 768) (100, 1)
(23391, 768) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT big final score: 0.67


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.6802
              precision    recall  f1-score   support

  akadēmisks       0.86      0.96      0.91        25
        citi       1.00      0.08      0.15        25
 darba laiks       0.69      1.00      0.82        25
   dokumenti       0.74      1.00      0.85        25

    accuracy                           0.76       100
   macro avg       0.82      0.76      0.68       100
weighted avg       0.82      0.76      0.68       100

[[24  0  0  1]
 [ 4  2 11  8]
 [ 0  0 25  0]
 [ 0  0  0 25]]
[[0.96 0.   0.   0.04]
 [0.16 0.08 0.44 0.32]
 [0.   0.   1.   0.  ]
 [0.   0.   0.   1.  ]]


<h3>OverSampling apjoms = 200%</h3>

In [0]:
from imblearn.under_sampling import NearMiss
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 3*122
thisdict = {
  1: size,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)
undersampler = NearMiss()

model_scores = []
counter = 0
for i in range(10):
  X_res, y_res = undersampler.fit_resample(features, target)                      # Veicam Unersampling
  X_res, y_res = oversampler.fit_resample(X_res, y_res)                           # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT big final score:',f1_final_score)

(100, 768) (100, 1)
(23391, 768) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT big final score: 0.69


In [0]:
from sklearn.metrics import f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)         # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

[[  0   1   2   3]
 [122 122 122 122]]
[[  0   1   2   3]
 [366 366 366 366]]
Keras Done
Naive Bayes F1 score: 0.7391
              precision    recall  f1-score   support

  akadēmisks       0.92      0.96      0.94        25
        citi       1.00      0.20      0.33        25
 darba laiks       0.76      1.00      0.86        25
   dokumenti       0.69      1.00      0.82        25

    accuracy                           0.79       100
   macro avg       0.84      0.79      0.74       100
weighted avg       0.84      0.79      0.74       100

[[24  0  0  1]
 [ 2  5  8 10]
 [ 0  0 25  0]
 [ 0  0  0 25]]
[[0.96 0.   0.   0.04]
 [0.08 0.2  0.32 0.4 ]
 [0.   0.   1.   0.  ]
 [0.   0.   0.   1.  ]]


<h3>OverSampling apjoms = 300%</h3>

In [0]:
from imblearn.under_sampling import NearMiss
from imblearn.over_sampling import BorderlineSMOTE
from keras import layers, models
from sklearn.metrics import f1_score
print(X.shape, Y.shape)
print(features.shape, target.shape)
y_test = Y.to_numpy()

size = 4*122
thisdict = {
  1: size,
  3: size,
  2: size,
  0: size
}
oversampler = BorderlineSMOTE(sampling_strategy=thisdict)
undersampler = NearMiss()

model_scores = []
counter = 0
for i in range(10):
  X_res, y_res = undersampler.fit_resample(features, target)                      # Veicam Unersampling
  X_res, y_res = oversampler.fit_resample(X_res, y_res)                           # Veicam Oversampling

  ### Keras Sequential ###
  model = models.Sequential()
  model.add(layers.Dense(256, activation='relu', input_shape=(col_count,)))
  model.add(layers.Dense(64, activation='relu'))
  model.add(layers.Dense(4, activation='softmax'))
  model.compile(loss=['sparse_categorical_crossentropy'],
                optimizer='adam',
                metrics=['sparse_categorical_crossentropy'])
  history = model.fit(X_res, y_res,
                      batch_size=64,
                      epochs=5,
                      verbose=0)
  y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
  keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
  f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)              # Fiksējam f1 vidējo rezultātu
  counter = counter + 1
  model_scores.append(f1_avg)
  print('Completed iteration #',counter)
f1_final_score = round(np.mean(model_scores),2)
print('BERT big final score:',f1_final_score)

(100, 768) (100, 1)
(23391, 768) (23391, 1)
Completed iteration # 1
Completed iteration # 2
Completed iteration # 3
Completed iteration # 4
Completed iteration # 5
Completed iteration # 6
Completed iteration # 7
Completed iteration # 8
Completed iteration # 9
Completed iteration # 10
BERT big final score: 0.67


In [0]:
from sklearn.metrics import plot_confusion_matrix, f1_score, classification_report, confusion_matrix
y_pred = model.predict(X)                                                       # Prasam modelim paredzēt testa datiem kategorijas
keras_y_pred = transformResults(y_pred)                                         # Pārveidojam rezultātus, paņemot ticamāko klasi no varbūtībām
y_test = Y.to_numpy()
class_names = ['akadēmisks', 'citi', 'darba laiks', 'dokumenti']
naive_f1_avg = round(f1_score(y_test, keras_y_pred, average='macro'),4)               # Fiksējam Naive Bayes f1 vidējo rezultātu
print('Naive Bayes F1 score:', naive_f1_avg)
print(classification_report(y_test, keras_y_pred, target_names=class_names))
print(confusion_matrix(y_test, keras_y_pred, normalize=None))
print(confusion_matrix(y_test, keras_y_pred, normalize='true'))

Naive Bayes F1 score: 0.7213
              precision    recall  f1-score   support

  akadēmisks       0.83      0.96      0.89        25
        citi       1.00      0.20      0.33        25
 darba laiks       0.83      0.96      0.89        25
   dokumenti       0.65      0.96      0.77        25

    accuracy                           0.77       100
   macro avg       0.83      0.77      0.72       100
weighted avg       0.83      0.77      0.72       100

[[24  0  0  1]
 [ 3  5  5 12]
 [ 1  0 24  0]
 [ 1  0  0 24]]
[[0.96 0.   0.   0.04]
 [0.12 0.2  0.2  0.48]
 [0.04 0.   0.96 0.  ]
 [0.04 0.   0.   0.96]]
